apiVersion: v1
kind: Service
metadata:
  name: zomato
  labels:
    app: zomato
spec:
  type: LoadBalancer
  selector:
    app: zomato
  ports:
    - protocol: TCP
      port: 80         # Exposes the service on port 80 (public)
      targetPort: 3000 # Forwards traffic to pod's port 3000
